import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import NavBar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function homeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-10 w-full bg-white">
          <div>
            <NavBar />
          </div>
          <div> {children}</div>
        </div>
      </body>
    </html>
  );
}
